# Generated by Django 6.0.1 on 2026-05-16 18:02

import django.db.models.deletion
from django.db import migrations, models

from core.models import default_avatar_config


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='eye_type',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='mouth_type',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='head_decoration',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='decoration_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='pattern_color',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_profile', to='core.user'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar_config',
            field=models.JSONField(blank=True, default=default_avatar_config),
        ),
    ]
