# Generated by Django 6.0.1 on 2026-05-17 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_achievements_user_last_active_user_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='helptutorial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newsannouncement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schoolanalyticsprofile',
            options={'verbose_name_plural': 'School Analytics Profiles'},
        ),
        migrations.RenameField(
            model_name='teachingresource',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='kindlewickgameprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='helptutorial',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='helptutorial',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='helptutorial',
            name='status',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='schoolanalyticsprofile',
            name='can_access_all_teachers',
        ),
        migrations.RemoveField(
            model_name='schoolanalyticsprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schoolanalyticsprofile',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='teachingresource',
            name='likes',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='allow_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='forum/uploads/'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('school', 'School Only')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='forumreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kindlewickgamesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='average_engagement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='safeguarding_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='total_forum_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='total_game_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='total_resources',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='total_teachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolanalyticsprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/uploads/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/images/'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helptutorial',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kindlewickgameprogress',
            name='game_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kindlewickgamesession',
            name='game_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolanalyticsprofile',
            name='school',
            field=models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='analytics',
            to='core.school'),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='resource_type',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='year_ks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ClassAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('average_xp', models.IntegerField(default=0)),
                ('total_resources', models.IntegerField(default=0)),
                ('total_discussions', models.IntegerField(default=0)),
                ('average_engagement', models.FloatField(default=0)),
                ('leaderboard_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clazz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.class')),
            ],
            options={
                'verbose_name_plural': 'Class Analytics',
            },
        ),
        migrations.CreateModel(
            name='ForumAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('moderation_actions', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.forumpost')),
            ],
            options={
                'verbose_name_plural': 'Forum Analytics',
            },
        ),
        migrations.CreateModel(
            name='ResourceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.teachingresource')),
            ],
            options={
                'verbose_name_plural': 'Resource Analytics',
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_logins', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('resources_viewed', models.IntegerField(default=0)),
                ('forum_posts', models.IntegerField(default=0)),
                ('forum_replies', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=100)),
                ('engagement_score', models.FloatField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Analytics',
            },
        ),
        migrations.CreateModel(
            name='ForumPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='core.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_likes', to='core.teachingresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resource', 'user')},
            },
        ),
    ]
