# Generated by Django 6.0.1 on 2026-05-18 05:46

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Class = apps.get_model('core', 'Class')
    for class_obj in Class.objects.all():
        if not class_obj.slug:
            base_slug = slugify(class_obj.name)
            slug = base_slug
            counter = 1
            # Ensure unique slug
            while Class.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            class_obj.slug = slug
            class_obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_avatar_options_alter_helptutorial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(populate_slugs),
        migrations.RunSQL(
            'DROP INDEX IF EXISTS "core_class_slug_e293aa55_like"',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
