# Generated by Django 6.0.1 on 2026-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_class_is_archived_class_slug_class_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='resource_type',
            field=models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('worksheet', 'Worksheet'), ('activity', 'Activity'), ('presentation', 'Presentation'), ('assessment', 'Assessment'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='year_ks',
            field=models.CharField(blank=True, choices=[('0', 'EYFS'), ('1', 'KS1'), ('2', 'KS2'), ('3', 'KS3'), ('4', 'KS4')], max_length=50),
        ),
    ]
