# Generated by Django 6.0.1 on 2026-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('EYFS', 'EYFS'), ('KS1', 'KS1'), ('LKS2', 'LKS2'), ('UKS2', 'UKS2'), ('KS3', 'KS3'), ('KS4', 'KS4'), ('SEND', 'SEND')], default='LKS2', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
