# Generated by Django 6.0.1 on 2026-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest_app", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        # Migration auto-generated earlier; fields are already present in initial migration.
        # Keep as a no-op to avoid duplicate column errors when running tests.
    ]
