# Generated by Django 6.0.1 on 2026-02-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quest_app", "0005_user_role_timestamps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="user_role_valid",
        ),
    ]
