# Generated by Django 6.0.1 on 2026-02-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0010_add_is_deleted_to_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plaintext_password', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
