# Generated by Django 6.0.1 on 2026-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0012_progress_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
