# Generated by Django 6.0.1 on 2026-02-19 09:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('school_admin', 'School Admin')], max_length=20)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('plain_password', models.CharField(blank=True, help_text='Plain text password for display purposes (students only)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Teacher Sign-up',
                'verbose_name_plural': 'Teacher Sign-ups',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('blob', 'Blob'), ('round', 'Round'), ('tall', 'Tall'), ('wide', 'Wide'), ('pear', 'Pear'), ('bean', 'Bean')], default='blob', max_length=20)),
                ('body_color', models.CharField(default='#FF6B9D', help_text='Hex color', max_length=7)),
                ('eye_type', models.CharField(choices=[('big_round', 'Big Round'), ('small_dots', 'Small Dots'), ('one_eye', 'One Eye'), ('sleepy', 'Sleepy'), ('googly', 'Googly'), ('angry', 'Angry')], default='big_round', max_length=20)),
                ('mouth_type', models.CharField(choices=[('happy', 'Happy'), ('toothy', 'Toothy'), ('small', 'Small'), ('big_smile', 'Big Smile'), ('oh', 'Oh'), ('silly', 'Silly')], default='happy', max_length=20)),
                ('head_decoration', models.CharField(choices=[('none', 'None'), ('horns', 'Horns'), ('antennae', 'Antennae'), ('spikes', 'Spikes'), ('ears', 'Ears'), ('mohawk', 'Mohawk')], default='horns', max_length=20)),
                ('decoration_color', models.CharField(default='#FFB347', help_text='Hex color', max_length=7)),
                ('pattern', models.CharField(choices=[('solid', 'Solid'), ('spots', 'Spots'), ('stripes', 'Stripes'), ('gradient', 'Gradient')], default='solid', max_length=20)),
                ('pattern_color', models.CharField(default='#FF1493', help_text='Hex color for spots/stripes', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatars',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('english', 'English'), ('maths', 'Maths'), ('english_maths', 'English and Maths')], max_length=100)),
                ('year_ks', models.CharField(choices=[('0', 'EYFS'), ('1', 'KS1'), ('2', 'KS2'), ('3', 'KS3'), ('4', 'KS4')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of forum')),
                ('is_locked', models.BooleanField(default=False, help_text='Prevent new replies')),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Post',
                'verbose_name_plural': 'Forum Posts',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.forumpost')),
            ],
            options={
                'verbose_name': 'Forum Reply',
                'verbose_name_plural': 'Forum Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary shown in listings', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='help_tutorials/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help & Tutorial',
                'verbose_name_plural': 'Help & Tutorials',
                'ordering': ['order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KindlewickGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('map', 'Map Exploration'), ('wizards_castle', 'Wizards Castle'), ('prefixes_potions', 'Prefixes and Potions'), ('grid_coordinator', 'Grid Coordinator')], max_length=50)),
                ('level', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('tokens_earned', models.IntegerField(default=0)),
                ('playtime', models.IntegerField(default=0, help_text='Playtime in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Game state/progress data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='kindlewick_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kindlewick Game Session',
                'verbose_name_plural': 'Kindlewick Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary shown in listings', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News & Announcement',
                'verbose_name_plural': 'News & Announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAnalyticsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('can_access_all_teachers', models.BooleanField(default=True, help_text="Access all teachers' data in the same school")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'School Analytics Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeachingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary shown in listings', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teaching_resources/images/')),
                ('file', models.FileField(blank=True, help_text='Upload PDF, Word, Excel files', null=True, upload_to='teaching_resources/')),
                ('resource_type', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('activity', 'Activity'), ('worksheet', 'Worksheet'), ('physical_material', 'Physical Material'), ('game_setup', 'Game Setup Guide'), ('other', 'Other')], default='other', max_length=20)),
                ('key_stage', models.IntegerField(blank=True, help_text='Key Stage (1-4)', null=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Featured resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_resources', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching Resource',
                'verbose_name_plural': 'Teaching Resources',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='resource_comments', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.teachingresource')),
            ],
            options={
                'verbose_name': 'Resource Comment',
                'verbose_name_plural': 'Resource Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.class')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Class Students',
                'unique_together': {('student', 'clazz')},
            },
        ),
        migrations.CreateModel(
            name='KindlewickGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('map', 'Map Exploration'), ('wizards_castle', 'Wizards Castle'), ('prefixes_potions', 'Prefixes and Potions'), ('grid_coordinator', 'Grid Coordinator')], max_length=50)),
                ('current_level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('tokens_earned', models.IntegerField(default=0)),
                ('total_playtime', models.IntegerField(default=0, help_text='Total playtime in seconds')),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='kindlewick_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kindlewick Game Progress',
                'verbose_name_plural': 'Kindlewick Game Progress',
                'ordering': ['-last_played'],
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
