# Generated by Django 6.0.1 on 2026-02-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_split_post_into_separate_models'),
    ]

    operations = [
    ]
