# Generated by Django 6.0.1 on 2026-02-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_gameevent_session_remove_gameevent_student_and_more'),
    ]

    operations = [
    ]
