# Generated by Django 6.0.1 on 2026-02-05 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_gameevent_session_remove_gameevent_student_and_more'),
    ]

    operations = [
    ]
