# Generated by Django 6.0.1 on 2026-02-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_resourcecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingresource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF, Word, Excel files', null=True, upload_to='teaching_resources/'),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
