# Generated by Django 6.0.1 on 2026-02-09 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_teachingresource_file_field'),
    ]

    operations = [
        # Add image fields to existing models
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_posts/'),
        ),
        migrations.AddField(
            model_name='helptutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help_tutorials/'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teaching_resources/images/'),
        ),
        
        # Update model options and fields
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Teacher Sign-up', 'verbose_name_plural': 'Teacher Sign-ups'},
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=10),
        ),
    ]
