# Generated by Django 6.0.1 on 2026-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_gameevent_session_remove_gameevent_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('school_admin', 'School Admin')], max_length=20),
        ),
    ]
