# Generated by Django 6.0.1 on 2026-02-09 10:22

from django.db import migrations


def create_admin_user(apps, schema_editor):
    """Create default admin user if it doesn't exist"""
    User = apps.get_model('core', 'User')
    
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin12345',
            role='teacher'
        )


def reverse_create_admin_user(apps, schema_editor):
    """Remove admin user if needed"""
    User = apps.get_model('core', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_gameevent_session_remove_gameevent_student_and_more'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
