# Generated by Django 6.0.1 on 2026-02-09 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_create_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('rectangular', 'Rectangular'), ('oval', 'Oval')], default='round', max_length=20)),
                ('body_color', models.CharField(default='#FF6B9D', max_length=7)),
                ('arm_style', models.CharField(choices=[('short', 'Short'), ('long', 'Long'), ('tentacle', 'Tentacle'), ('none', 'None')], default='short', max_length=20)),
                ('arm_color', models.CharField(default='#FF6B9D', max_length=7)),
                ('leg_style', models.CharField(choices=[('two', 'Two Legs'), ('four', 'Four Legs'), ('none', 'No Legs')], default='two', max_length=20)),
                ('leg_color', models.CharField(default='#FF6B9D', max_length=7)),
                ('eye_style', models.CharField(choices=[('round', 'Round'), ('oval', 'Oval'), ('closed', 'Closed'), ('star', 'Star')], default='round', max_length=20)),
                ('eye_color', models.CharField(default='#000000', max_length=7)),
                ('mouth_style', models.CharField(choices=[('smile', 'Smile'), ('frown', 'Frown'), ('neutral', 'Neutral'), ('open', 'Open')], default='smile', max_length=20)),
                ('mouth_color', models.CharField(default='#000000', max_length=7)),
                ('has_teeth', models.BooleanField(default=False)),
                ('has_glasses', models.BooleanField(default=False)),
                ('has_ears', models.BooleanField(default=False)),
                ('has_antennae', models.BooleanField(default=False)),
                ('has_shoes', models.BooleanField(default=False)),
                ('shoe_color', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatars',
            },
        ),
    ]
