# Generated by Django 6.0.1 on 2026-02-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_avatar_remove_gameevent_session_and_more'),
    ]

    operations = [
    ]
