# Generated by Django 6.0.1 on 2026-02-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_final_cleanup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameEvent',
        ),
        migrations.DeleteModel(
            name='LearningObjective',
        ),
        migrations.DeleteModel(
            name='ObjectiveAttempt',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='StudentObjectiveMastery',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
