# Generated by Django 6.0.1 on 2026-02-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_old_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
    ]
