# Generated by Django 6.0.1 on 2026-02-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_user_last_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='bow_color',
            field=models.CharField(default='#FF6B9D', max_length=7),
        ),
        migrations.AddField(
            model_name='avatar',
            name='bow_style',
            field=models.CharField(choices=[('none', 'None'), ('left', 'Left'), ('right', 'Right'), ('top', 'Top')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='ear_style',
            field=models.CharField(choices=[('round', 'Round'), ('floppy', 'Floppy'), ('pointy', 'Pointy')], default='round', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='has_glow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='has_shading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='has_shadow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='has_sparkles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avatar',
            name='hat_color',
            field=models.CharField(default='#A78BFA', max_length=7),
        ),
        migrations.AddField(
            model_name='avatar',
            name='hat_style',
            field=models.CharField(choices=[('none', 'None'), ('beanie', 'Beanie'), ('party', 'Party')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='horn_style',
            field=models.CharField(choices=[('none', 'None'), ('small', 'Small'), ('curved', 'Curved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='jumper_color',
            field=models.CharField(default='#FFF2CC', max_length=7),
        ),
        migrations.AddField(
            model_name='avatar',
            name='jumper_pattern',
            field=models.CharField(choices=[('none', 'None'), ('stripes', 'Stripes'), ('dots', 'Dots'), ('zigzag', 'Zigzag'), ('hearts', 'Hearts')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='nose_style',
            field=models.CharField(choices=[('none', 'None'), ('button', 'Button'), ('triangle', 'Triangle'), ('stitch', 'Stitch')], default='button', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='pattern_color',
            field=models.CharField(default='#F7A7C6', max_length=7),
        ),
        migrations.AddField(
            model_name='avatar',
            name='tail_style',
            field=models.CharField(choices=[('none', 'None'), ('short', 'Short'), ('long', 'Long'), ('curled', 'Curled')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='texture_style',
            field=models.CharField(choices=[('fuzzy', 'Fuzzy'), ('stitched', 'Stitched'), ('quilted', 'Quilted'), ('smooth', 'Smooth')], default='fuzzy', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='has_ears',
            field=models.BooleanField(default=True),
        ),
    ]
