# Generated by Django 6.0.1 on 2026-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_avatar_bow_color_avatar_bow_style_avatar_ear_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='arm_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='arm_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='body_shape',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='bow_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='bow_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='ear_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='eye_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_antennae',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_ears',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_glasses',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_glow',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_shading',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_shadow',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_shoes',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_sparkles',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='has_teeth',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='hat_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='hat_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='horn_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='jumper_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='jumper_pattern',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='leg_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='leg_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='mouth_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='nose_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='pattern_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='shoe_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='tail_style',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='texture_style',
        ),
        migrations.AddField(
            model_name='avatar',
            name='accessory_1',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('glasses', 'Glasses'), ('badge', 'Badge'), ('bow', 'Bow'), ('hat', 'Hat')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='accessory_2',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('glasses', 'Glasses'), ('badge', 'Badge'), ('bow', 'Bow'), ('hat', 'Hat')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='base_face',
            field=models.CharField(choices=[('round', 'Round Face'), ('oval', 'Oval Face')], default='round', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='clothes_style',
            field=models.CharField(choices=[('teacher_cardigan', 'Teacher Cardigan'), ('teacher_blazer', 'Teacher Blazer'), ('student_uniform', 'Student Uniform'), ('student_hoodie', 'Student Hoodie'), ('casual_shirt', 'Casual Shirt')], default='casual_shirt', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='eyebrows_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('happy', 'Happy'), ('surprised', 'Surprised')], default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='eyes_style',
            field=models.CharField(choices=[('happy_blue', 'Happy Blue Eyes'), ('sleepy_green', 'Sleepy Green Eyes'), ('cute_brown', 'Cute Brown Eyes'), ('sparkle_purple', 'Sparkle Purple Eyes')], default='happy_blue', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(default='#8B4513', help_text='Hex color override', max_length=7),
        ),
        migrations.AddField(
            model_name='avatar',
            name='hair_style',
            field=models.CharField(choices=[('short_brown', 'Short Brown'), ('long_black', 'Long Black'), ('medium_blonde', 'Medium Blonde'), ('spiky_red', 'Spiky Red')], default='short_brown', max_length=30),
        ),
        migrations.AddField(
            model_name='avatar',
            name='skin_tone',
            field=models.CharField(default='#FFE0BD', help_text='Hex color', max_length=7),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='mouth_style',
            field=models.CharField(choices=[('smile', 'Smile'), ('open', 'Open Smile'), ('neutral', 'Neutral'), ('small', 'Small Smile')], default='smile', max_length=30),
        ),
    ]
