# Generated by Django 6.0.1 on 2026-02-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='primary_color',
            new_name='body_color',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='accent_color',
            new_name='decoration_color',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='accessory',
        ),
        migrations.AddField(
            model_name='avatar',
            name='head_decoration',
            field=models.CharField(choices=[('none', 'None'), ('horns', 'Horns'), ('antennae', 'Antennae'), ('spikes', 'Spikes'), ('ears', 'Ears'), ('mohawk', 'Mohawk')], default='horns', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='pattern',
            field=models.CharField(choices=[('solid', 'Solid'), ('spots', 'Spots'), ('stripes', 'Stripes'), ('gradient', 'Gradient')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='pattern_color',
            field=models.CharField(default='#FF1493', help_text='Hex color for spots/stripes', max_length=7),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='body_type',
            field=models.CharField(choices=[('blob', 'Blob'), ('round', 'Round'), ('tall', 'Tall'), ('wide', 'Wide'), ('pear', 'Pear'), ('bean', 'Bean')], default='blob', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='eye_type',
            field=models.CharField(choices=[('big_round', 'Big Round'), ('small_dots', 'Small Dots'), ('one_eye', 'One Eye'), ('sleepy', 'Sleepy'), ('googly', 'Googly'), ('angry', 'Angry')], default='big_round', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='mouth_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('toothy', 'Toothy'), ('small', 'Small'), ('big_smile', 'Big Smile'), ('oh', 'Oh'), ('silly', 'Silly')], default='happy', max_length=20),
        ),
    ]
