# Generated by Django 6.0.1 on 2026-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year_ks',
            field=models.IntegerField(choices=[(0, 'EYFS'), (1, 'KS1'), (2, 'KS2'), (3, 'KS3'), (4, 'KS4')]),
        ),
    ]
