# Generated by Django 6.0.1 on 2026-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_class_year_ks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('maths', 'Maths'), ('english_maths', 'English and Maths')], max_length=100),
        ),
    ]
