# Generated by Django 6.0.1 on 2026-02-11 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindlewickGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('map', 'Map Exploration'), ('wizards_castle', 'Wizards Castle'), ('prefixes_potions', 'Prefixes and Potions'), ('grid_coordinator', 'Grid Coordinator')], max_length=50)),
                ('level', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('tokens_earned', models.IntegerField(default=0)),
                ('playtime', models.IntegerField(default=0, help_text='Playtime in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Game state/progress data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='kindlewick_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kindlewick Game Session',
                'verbose_name_plural': 'Kindlewick Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KindlewickGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('map', 'Map Exploration'), ('wizards_castle', 'Wizards Castle'), ('prefixes_potions', 'Prefixes and Potions'), ('grid_coordinator', 'Grid Coordinator')], max_length=50)),
                ('current_level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('tokens_earned', models.IntegerField(default=0)),
                ('total_playtime', models.IntegerField(default=0, help_text='Total playtime in seconds')),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='kindlewick_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kindlewick Game Progress',
                'verbose_name_plural': 'Kindlewick Game Progress',
                'ordering': ['-last_played'],
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
